name: Auto Author Assign

on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  assign-author:
    name: Auto Author Assign
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v1.3.7
        with:
          repo-token: "${{ secrets.PAT_GITHUB_ACTIONS }}"
